#!/bin/sh

# lib
rm -f /usr/lib/libimobiledevice.a
rm -f /usr/lib/libimobiledevice.so
rm -f /usr/lib/libimobiledevice.so.6.0.0
rm -f /usr/lib/libusbmuxd.la
rm -f /usr/lib/libusbmuxd.so.4
rm -f /usr/lib/libimobiledevice.la
rm -f /usr/lib/libimobiledevice.so.6
rm -f /usr/lib/libusbmuxd.a
rm -f /usr/lib/libusbmuxd.so
rm -f /usr/lib/libusbmuxd.so.4.0.0
rm -f /usr/lib/libusb-1.0.so.0
rm -f /usr/lib/libusb-1.0.so.0.1.0
rm -f /usr/lib/libudev.so.1.6.4
rm -f /usr/lib/libudev.so.1

# bin
rm -f /usr/bin/idevicebackup
rm -f /usr/bin/idevicedebug
rm -f /usr/bin/idevice_id
rm -f /usr/bin/idevicenotificationproxy
rm -f /usr/bin/idevicesyslog
rm -f /usr/bin/idevicebackup2
rm -f /usr/bin/idevicedebugserverproxy
rm -f /usr/bin/ideviceimagemounter
rm -f /usr/bin/idevicepair
rm -f /usr/bin/ifuse
rm -f /usr/bin/idevicecrashreport
rm -f /usr/bin/idevicediagnostics
rm -f /usr/bin/ideviceinfo
rm -f /usr/bin/ideviceprovision
rm -f /usr/bin/iproxy
rm -f /usr/bin/idevicedate
rm -f /usr/bin/ideviceenterrecovery
rm -f /usr/bin/idevicename
rm -f /usr/bin/idevicescreenshot

# sbin
rm -f /usr/sbin/postuninst

# udev
rm -f /usr/lib/udev/rules.d/39-libimobiledevice.rules
exit 0
